import Foundation

/// The accuracy benchmark — the product's reason to exist measured, not guessed
/// (DESIGN §3). Synthesizes pure / harmonic / inharmonic tones across the full
/// guitar+bass range at known cents, runs them through the real pipeline, and
/// reports cents error (mean/abs/σ), a separate **held-note lock-window** score,
/// time-to-lock, octave-error rate, noise robustness, the CRLB floor, and a set
/// of **stress** case families (decay-glide, vibrato, weak/missing fundamental).
/// Deterministic (seeded noise).
///
/// P0 makes the sub-0.1 ¢ wins *measurable* without changing the engine: the
/// stress families and lock-window σ are reported but kept out of the headline
/// pool, so the core numbers stay comparable and the CI gate stays stable while
/// P1–P3 land the estimators that earn the tighter targets (Plan 06 §9, §10).
public enum BenchmarkSuite {

    public enum Signal: String, CaseIterable { case pure, harmonic, inharmonic }

    /// Output bundle.
    public struct Report {
        public let csv: String
        public let markdown: String
        public let summary: Summary
    }

    /// Headline numbers the app/DESIGN can quote (and the `--ci` gate reads).
    public struct Summary: Sendable {
        public let method: DetectionMethod
        public let cleanAbsCents: Double
        public let cleanSigma: Double
        public let lockSigma: Double          // pooled held-note lock-window σ (clean core)
        public let octaveErrorRate: Double
        public let worstAbsCents: Double
        public let bassAbsCents: Double
        public let bassWorstCents: Double
        public let midAbsCents: Double
        public let highAbsCents: Double
        public let lockMSMedian: Double
        public let stressOctaveErrors: Int    // octave errors across stress families
        public let stressWorstAbsCents: Double
        public let cases: Int
    }

    // The bench matrix: low B (5-string) up to high frets.
    private static let notes: [Int] = [
        23,          // B0  (5-string low B, ~30.9 Hz)
        28, 33, 38, 43,   // bass E1 A1 D2 G2
        40, 45, 50, 55, 59, 64,  // guitar E2 A2 D3 G3 B3 E4
        76, 88       // E5, E6
    ]
    private static let centsOffsets: [Double] = [-50, -20, 0, 20, 50]

    // Stress families — real-world realities the default ∝1/k model never
    // exercises. Reported separately so they don't move the core headline.
    private static let weakFundNotes = [23, 28, 33, 40]   // B0 E1 A1 E2
    private static let glideNotes    = [28, 40, 50, 64]   // E1 E2 D3 E4
    private static let vibratoNotes  = [40, 55, 64]       // E2 G3 E4
    private static let noiseNotes    = [28, 40, 55, 64]
    private static let noiseSNRs     = [40.0, 20.0, 10.0, 5.0]

    /// Held-note lock window opens at 1.0 s; stimuli run long enough to score it.
    static let lockWindowStart: TimeInterval = 1.0
    private static func coreSeconds(_ f: Double) -> Double { f < 80 ? 2.6 : 2.0 }

    /// Run the full benchmark for one method.
    public static func run(
        method: DetectionMethod = .mpm,
        sampleRate: Double = 48_000,
        a4: Double = Pitch.standardA4,
        dateLabel: String = "(generated by Benchmark)"
    ) -> Report {
        var clean: [CaseResult] = []
        var noise: [CaseResult] = []
        var stress: [CaseResult] = []

        // Clean matrix: every note × signal × cents offset.
        for midi in notes {
            let base = Pitch.frequency(midi: midi, a4: a4)
            let seconds = coreSeconds(base)
            for signal in Signal.allCases {
                for cents in centsOffsets {
                    let f = Synth.detune(base, cents: cents)
                    let buf = synth(signal, frequency: f, sampleRate: sampleRate, seconds: seconds)
                    clean.append(runCase(buf, sampleRate, f, signal.rawValue, cents, .infinity, method, a4))
                }
            }
        }

        // Noise robustness: a representative subset across SNRs (now incl. 5 dB).
        var rng = SeededRNG(seed: 0xA5A5_1234_BEEF)
        for midi in noiseNotes {
            let base = Pitch.frequency(midi: midi, a4: a4)
            for snr in noiseSNRs {
                let cleanBuf = synth(.inharmonic, frequency: base, sampleRate: sampleRate, seconds: 2.0)
                let noisy = Synth.addNoise(to: cleanBuf, snrDB: snr, rng: &rng)
                noise.append(runCase(noisy, sampleRate, base, "inharmonic+noise", 0, snr, method, a4))
            }
        }

        // Stress families.
        for midi in weakFundNotes {
            let base = Pitch.frequency(midi: midi, a4: a4)
            stress.append(runCase(Synth.inharmonicString(fundamental: base, sampleRate: sampleRate, seconds: 2.2, fundamentalLevel: 0.15),
                                  sampleRate, base, "weak-fund", 0, .infinity, method, a4))
            stress.append(runCase(Synth.inharmonicString(fundamental: base, sampleRate: sampleRate, seconds: 2.2, fundamentalLevel: 0),
                                  sampleRate, base, "missing-fund", 0, .infinity, method, a4))
        }
        for midi in glideNotes {
            let base = Pitch.frequency(midi: midi, a4: a4)
            stress.append(runCase(Synth.decayGlide(settledFrequency: base, sampleRate: sampleRate, seconds: 2.2),
                                  sampleRate, base, "decay-glide", 0, .infinity, method, a4))
        }
        for midi in vibratoNotes {
            let base = Pitch.frequency(midi: midi, a4: a4)
            stress.append(runCase(Synth.vibrato(centerFrequency: base, sampleRate: sampleRate, seconds: 2.2),
                                  sampleRate, base, "vibrato", 0, .infinity, method, a4))
        }

        let summary = summarize(clean: clean, stress: stress, method: method)
        let all = clean + noise
        return Report(
            csv: csv(all + stress),
            markdown: markdown(clean: clean, noise: noise, stress: stress,
                               summary: summary, sampleRate: sampleRate, a4: a4, dateLabel: dateLabel),
            summary: summary
        )
    }

    /// Compact MPM vs YIN vs hybrid comparison (let the benchmark pick a default).
    public static func compareMethods(sampleRate: Double = 48_000, a4: Double = Pitch.standardA4)
        -> [Summary] {
        let subset = [28, 40, 45, 55, 64, 76]
        return DetectionMethod.allCases.map { method in
            var clean: [CaseResult] = []
            for midi in subset {
                let base = Pitch.frequency(midi: midi, a4: a4)
                let seconds = base < 80 ? 1.2 : 0.6
                for signal in Signal.allCases {
                    for cents in [-20.0, 0, 20] {
                        let f = Synth.detune(base, cents: cents)
                        let buf = synth(signal, frequency: f, sampleRate: sampleRate, seconds: seconds)
                        clean.append(runCase(buf, sampleRate, f, signal.rawValue, cents, .infinity, method, a4))
                    }
                }
            }
            return summarize(clean: clean, stress: [], method: method)
        }
    }

    // MARK: - Case dispatch

    private static func runCase(
        _ buf: [Float], _ sampleRate: Double, _ f: Double, _ category: String,
        _ cents: Double, _ snr: Double, _ method: DetectionMethod, _ a4: Double
    ) -> CaseResult {
        CaseRunner.run(signal: buf, sampleRate: sampleRate, trueFrequency: f,
                       category: category, centsTarget: cents, snrDB: snr,
                       method: method, a4: a4, lockWindowStart: lockWindowStart)
    }

    private static func synth(_ s: Signal, frequency: Double, sampleRate: Double, seconds: Double) -> [Float] {
        switch s {
        case .pure: return Synth.pure(frequency: frequency, sampleRate: sampleRate, seconds: seconds)
        case .harmonic: return Synth.harmonic(fundamental: frequency, sampleRate: sampleRate, seconds: seconds)
        case .inharmonic: return Synth.inharmonicString(fundamental: frequency, sampleRate: sampleRate, seconds: seconds)
        }
    }

    // MARK: - Aggregation

    private static func summarize(clean: [CaseResult], stress: [CaseResult], method: DetectionMethod) -> Summary {
        let pooled = ErrorStats.from(clean.flatMap { $0.errors })
        let lockPooled = ErrorStats.from(clean.flatMap { $0.lockErrors })
        let bassPooled = ErrorStats.from(clean.filter { bucket($0.trueFrequency) == bands[0] }.flatMap { $0.errors })
        let midPooled = ErrorStats.from(clean.filter { bucket($0.trueFrequency) == bands[1] }.flatMap { $0.errors })
        let highPooled = ErrorStats.from(clean.filter { bucket($0.trueFrequency) == bands[2] }.flatMap { $0.errors })
        let octRate = clean.isEmpty ? 0 : Double(clean.filter { $0.octaveError }.count) / Double(clean.count)
        let locks = clean.compactMap { $0.timeToLockMS }.sorted()
        let lockMedian = locks.isEmpty ? 0 : locks[locks.count / 2]
        let stressWorst = stress.map { $0.stats.maxAbs }.max() ?? 0
        return Summary(
            method: method,
            cleanAbsCents: pooled.meanAbs,
            cleanSigma: pooled.sigma,
            lockSigma: lockPooled.sigma,
            octaveErrorRate: octRate,
            worstAbsCents: pooled.maxAbs,
            bassAbsCents: bassPooled.meanAbs,
            bassWorstCents: bassPooled.maxAbs,
            midAbsCents: midPooled.meanAbs,
            highAbsCents: highPooled.meanAbs,
            lockMSMedian: lockMedian,
            stressOctaveErrors: stress.filter { $0.octaveError }.count,
            stressWorstAbsCents: stressWorst,
            cases: clean.count + stress.count
        )
    }

    private static let bands = ["bass (<82 Hz)", "mid (82–330 Hz)", "high (>330 Hz)"]
    private static func bucket(_ f: Double) -> String {
        if f < 82 { return bands[0] }
        if f < 330 { return bands[1] }
        return bands[2]
    }

    // MARK: - CSV

    private static func csv(_ results: [CaseResult]) -> String {
        var lines = ["category,note,true_hz,cents_target,snr_db,n,mean_cents,abs_cents,sigma_cents,max_abs_cents,lock_abs_cents,lock_sigma_cents,octave_error,lock_ms"]
        for r in results {
            let snr = r.snrDB.isFinite ? f2(r.snrDB) : "inf"
            let lock = r.timeToLockMS.map { f1($0) } ?? ""
            lines.append([
                r.category, r.note, f2(r.trueFrequency), f1(r.centsTarget), snr,
                "\(r.readings)", f3(r.stats.mean), f3(r.stats.meanAbs), f3(r.stats.sigma),
                f3(r.stats.maxAbs), f3(r.lockStats.meanAbs), f3(r.lockStats.sigma),
                r.octaveError ? "1" : "0", lock
            ].joined(separator: ","))
        }
        return lines.joined(separator: "\n")
    }

    // MARK: - Markdown

    private static func markdown(
        clean: [CaseResult], noise: [CaseResult], stress: [CaseResult],
        summary: Summary, sampleRate: Double, a4: Double, dateLabel: String
    ) -> String {
        var md = ""
        md += "# TunerEngine — measured accuracy\n\n"
        md += "_\(dateLabel). Method: **\(summary.method.rawValue.uppercased())**, "
        md += "\(Int(sampleRate)) Hz, A4 = \(Int(a4)) Hz. Deterministic (seeded)._\n\n"
        md += "> Regenerate: `swift run -c release --package-path Packages/TunerEngine Benchmark --out docs/benchmarks`. "
        md += "CI (macOS) regenerates this every build as an artifact; this committed copy is the published spec.\n\n"

        md += "## Headline\n\n"
        md += "| Metric | Value |\n|---|---|\n"
        md += "| Mean abs cents error (clean) | **\(f2(summary.cleanAbsCents))¢** |\n"
        md += "| Jitter σ (clean, steady) | \(f2(summary.cleanSigma))¢ |\n"
        md += "| **Held-note lock-window σ (clean)** | \(f2(summary.lockSigma))¢ |\n"
        md += "| Worst-case abs error (clean) | \(f2(summary.worstAbsCents))¢ |\n"
        md += "| Octave-error rate (clean) | \(f2(summary.octaveErrorRate * 100))% |\n"
        md += "| Median time-to-lock (cold start) | \(f0(summary.lockMSMedian)) ms |\n"
        md += "| Clean cases / stress cases | \(clean.count) / \(stress.count) |\n\n"

        md += "## By signal type (clean)\n\n"
        md += "| Signal | n | mean ¢ | abs ¢ | σ ¢ | max ¢ |\n|---|---|---|---|---|---|\n"
        for s in Signal.allCases {
            let p = ErrorStats.from(clean.filter { $0.category == s.rawValue }.flatMap { $0.errors })
            md += "| \(s.rawValue) | \(p.count) | \(f2(p.mean)) | \(f2(p.meanAbs)) | \(f2(p.sigma)) | \(f2(p.maxAbs)) |\n"
        }

        md += "\n## By range (clean) — steady vs held-note lock window\n\n"
        md += "| Range | n | abs ¢ | σ ¢ | max ¢ | lock abs ¢ | lock σ ¢ |\n|---|---|---|---|---|---|---|\n"
        for b in bands {
            let inB = clean.filter { bucket($0.trueFrequency) == b }
            let p = ErrorStats.from(inB.flatMap { $0.errors })
            let lp = ErrorStats.from(inB.flatMap { $0.lockErrors })
            md += "| \(b) | \(p.count) | \(f2(p.meanAbs)) | \(f2(p.sigma)) | \(f2(p.maxAbs)) | \(f2(lp.meanAbs)) | \(f2(lp.sigma)) |\n"
        }

        md += "\n## Stress cases (reported, not pooled into the headline)\n\n"
        md += "Real-world realities the default model omits — the families P1–P3 must "
        md += "improve. Today they run on the current engine as a baseline.\n\n"
        md += "| Family | n | abs ¢ | σ ¢ | lock σ ¢ | max ¢ | octave err |\n|---|---|---|---|---|---|---|\n"
        for fam in ["weak-fund", "missing-fund", "decay-glide", "vibrato"] {
            let inF = stress.filter { $0.category == fam }
            guard !inF.isEmpty else { continue }
            let p = ErrorStats.from(inF.flatMap { $0.errors })
            let lp = ErrorStats.from(inF.flatMap { $0.lockErrors })
            let oct = inF.filter { $0.octaveError }.count
            md += "| \(fam) | \(p.count) | \(f2(p.meanAbs)) | \(f2(p.sigma)) | \(f2(lp.sigma)) | \(f2(p.maxAbs)) | \(oct) |\n"
        }

        md += "\n## Noise robustness (inharmonic, abs cents vs SNR)\n\n"
        md += "| SNR (dB) | n | abs ¢ | σ ¢ | lock σ ¢ | octave errors |\n|---|---|---|---|---|---|\n"
        for snr in noiseSNRs {
            let subset = noise.filter { $0.snrDB == snr }
            let p = ErrorStats.from(subset.flatMap { $0.errors })
            let lp = ErrorStats.from(subset.flatMap { $0.lockErrors })
            let oct = subset.filter { $0.octaveError }.count
            md += "| \(Int(snr)) | \(p.count) | \(f2(p.meanAbs)) | \(f2(p.sigma)) | \(f2(lp.sigma)) | \(oct) |\n"
        }

        md += crlbSection(noise: noise, sampleRate: sampleRate)

        md += "\n## Octave safety on low strings (clean, 0¢)\n\n"
        md += "| Note | true Hz | abs ¢ | octave error |\n|---|---|---|---|\n"
        for midi in [23, 28, 33, 38, 43] {
            let f = Pitch.frequency(midi: midi, a4: a4)
            if let r = clean.first(where: { $0.category == "inharmonic" && abs($0.trueFrequency - f) < 0.5 }) {
                md += "| \(r.note) | \(f2(f)) | \(f2(r.stats.meanAbs)) | \(r.octaveError ? "⚠️ yes" : "no") |\n"
            }
        }

        md += "\n## Window / hop strategy (48 kHz)\n\n"
        md += "| Band | f0 | Window | Hop | Overlap |\n|---|---|---|---|---|\n"
        md += "| high | ≥250 Hz | 1024 (21 ms) | 256 (5.3 ms) | 75% |\n"
        md += "| mid | 120–250 Hz | 2048 (43 ms) | 512 (11 ms) | 75% |\n"
        md += "| low | <120 Hz | 4096 (85 ms) | 1024 (21 ms) | 75% |\n"
        md += "| acquire (cold) | unknown | 4096 (85 ms) | 1024 (21 ms) | 75% |\n\n"

        md += "## Method\n\n"
        md += "Each case synthesizes ~2–2.6 s of tone at a known frequency, feeds it through a fresh "
        md += "`PitchPipeline` in ~10 ms blocks, and scores the **steady-state** readings (after 300 ms). "
        md += "The **lock window** scores only the later, held region (after \(f1(lockWindowStart)) s) — where a "
        md += "strobe-grade tuner should drive σ to the noise floor; P3's phase-slope integrator is what "
        md += "earns it. Cents error is signal-relative (`1200·log₂(estimate/true)`), not quantised to the "
        md += "nearest note. Inharmonic tones use the stiff-string law `f_k = k·f0·√(1+B·k²)`. The CRLB is "
        md += "the Cramér–Rao floor (Rife–Boorstyn / Christensen); see `Bench/Crlb.swift`. Numbers are "
        md += "reproducible via `swift run Benchmark`.\n"
        return md
    }

    /// CRLB floor + measured efficiency on a held E2 (the low-string worst case),
    /// scored at the band window N=4096. The harmonic floor uses the *actual*
    /// ∝1/k partial weights — far weaker than an equal-amplitude analysis, the
    /// honest reason the harmonic floor sits where it does (Plan 06 §2.3, §9).
    private static func crlbSection(noise: [CaseResult], sampleRate fs: Double) -> String {
        let f0 = 82.41, N = 4096
        let amps = (1...10).map { 0.5 / Double($0) }                 // ∝1/k (scale cancels)
        let W = Crlb.normalizedHarmonicWeight(amplitudes: amps)      // ≈ 6.45
        var md = "\n## CRLB floor & efficiency (held E2, N=4096)\n\n"
        md += "Physical limit (single-tone vs harmonic, ∝1/k weight \(f2(W))), and the measured held-note "
        md += "σ as a multiple of it. Today's σ sits far above the floor — that gap is the P2/P3 headroom, "
        md += "now visible.\n\n"
        md += "| SNR (dB) | CRLB σ single ¢ | CRLB σ harmonic ¢ | measured lock σ ¢ | σ / harmonic floor |\n"
        md += "|---|---|---|---|---|\n"
        for snr in noiseSNRs {
            let single = Crlb.boundCentsSingle(sampleRate: fs, n: N, snrDB: snr, f0: f0)
            let harm = Crlb.boundCentsHarmonic(sampleRate: fs, n: N, snrDB: snr, f0: f0, harmonicWeight: W)
            let e2 = noise.first { $0.snrDB == snr && abs($0.trueFrequency - f0) < 0.5 }
            let measured = (e2?.lockStats.sigma ?? e2?.stats.sigma) ?? .nan
            let eff = measured / harm
            let effStr = eff < 10 ? f1(eff) : f0fmt(eff)
            md += "| \(Int(snr)) | \(f4(single)) | \(f4(harm)) | \(measured.isNaN ? "—" : f3(measured)) | "
            md += "\(measured.isNaN ? "—" : effStr)× |\n"
        }
        md += "\n_Absolute-pitch clock floor: a device sample clock off by N ppm reads "
        md += "`1200·log₂(1+N/10⁶)` ¢ sharp — 44 ppm ≈ \(f3(Crlb.centsFromPPM(44)))¢, 100 ppm ≈ "
        md += "\(f3(Crlb.centsFromPPM(100)))¢ (1 ¢ = \(f0fmt(Crlb.ppmPerCent)) ppm). Relative/strobe tuning is "
        md += "clock-immune; absolute is clock-bound until calibrated (Plan 06 §3, §7; P4)._\n"
        return md
    }

    // Formatting helpers.
    private static func f0(_ x: Double) -> String { String(format: "%.0f", x) }
    private static func f0fmt(_ x: Double) -> String { String(format: "%.0f", x) }
    private static func f1(_ x: Double) -> String { String(format: "%.1f", x) }
    private static func f2(_ x: Double) -> String { String(format: "%.2f", x) }
    private static func f3(_ x: Double) -> String { String(format: "%.3f", x) }
    private static func f4(_ x: Double) -> String { String(format: "%.4f", x) }
}
