import Foundation

/// The accuracy benchmark — the product's reason to exist measured, not guessed
/// (DESIGN §3). Synthesizes pure / harmonic / inharmonic tones across the full
/// guitar+bass range at known cents, runs them through the real pipeline, and
/// reports cents error (mean/abs/σ), time-to-lock, octave-error rate, and noise
/// robustness as a CSV + a Markdown spec. Deterministic (seeded noise).
public enum BenchmarkSuite {

    public enum Signal: String, CaseIterable { case pure, harmonic, inharmonic }

    /// A note under test (MIDI number drives the true frequency).
    struct TestNote { let midi: Int }

    /// Output bundle.
    public struct Report {
        public let csv: String
        public let markdown: String
        public let summary: Summary
    }

    /// Headline numbers the app/DESIGN can quote.
    public struct Summary: Sendable {
        public let method: DetectionMethod
        public let cleanAbsCents: Double
        public let cleanSigma: Double
        public let octaveErrorRate: Double
        public let worstAbsCents: Double
        public let lockMSMedian: Double
        public let cases: Int
    }

    // The bench matrix: low B (5-string) up to high frets.
    private static let notes: [Int] = [
        23,          // B0  (5-string low B, ~30.9 Hz)
        28, 33, 38, 43,   // bass E1 A1 D2 G2
        40, 45, 50, 55, 59, 64,  // guitar E2 A2 D3 G3 B3 E4
        76, 88       // E5, E6
    ]
    private static let centsOffsets: [Double] = [-50, -20, 0, 20, 50]

    /// Run the full benchmark for one method.
    public static func run(
        method: DetectionMethod = .mpm,
        sampleRate: Double = 48_000,
        a4: Double = Pitch.standardA4,
        dateLabel: String = "(generated by Benchmark)"
    ) -> Report {
        var results: [CaseResult] = []

        // Clean matrix: every note × signal × cents offset.
        for midi in notes {
            let base = Pitch.frequency(midi: midi, a4: a4)
            let seconds = base < 80 ? 1.2 : 0.6
            for signal in Signal.allCases {
                for cents in centsOffsets {
                    let f = Synth.detune(base, cents: cents)
                    let buf = synth(signal, frequency: f, sampleRate: sampleRate, seconds: seconds)
                    results.append(CaseRunner.run(
                        signal: buf, sampleRate: sampleRate, trueFrequency: f,
                        category: signal.rawValue, centsTarget: cents, snrDB: .infinity,
                        method: method, a4: a4))
                }
            }
        }

        // Noise robustness: a representative subset across SNRs.
        var rng = SeededRNG(seed: 0xA5A5_1234_BEEF)
        let noiseNotes = [28, 40, 55, 64]
        for midi in noiseNotes {
            let base = Pitch.frequency(midi: midi, a4: a4)
            let seconds = base < 80 ? 1.2 : 0.6
            for snr in [40.0, 20.0, 10.0] {
                let clean = synth(.inharmonic, frequency: base, sampleRate: sampleRate, seconds: seconds)
                let noisy = Synth.addNoise(to: clean, snrDB: snr, rng: &rng)
                results.append(CaseRunner.run(
                    signal: noisy, sampleRate: sampleRate, trueFrequency: base,
                    category: "inharmonic+noise", centsTarget: 0, snrDB: snr,
                    method: method, a4: a4))
            }
        }

        let summary = summarize(results, method: method)
        return Report(
            csv: csv(results),
            markdown: markdown(results, summary: summary, sampleRate: sampleRate, a4: a4, dateLabel: dateLabel),
            summary: summary
        )
    }

    /// Compact MPM vs YIN vs hybrid comparison (let the benchmark pick a default).
    public static func compareMethods(sampleRate: Double = 48_000, a4: Double = Pitch.standardA4)
        -> [Summary] {
        let subset = [28, 40, 45, 55, 64, 76]
        return DetectionMethod.allCases.map { method in
            var results: [CaseResult] = []
            for midi in subset {
                let base = Pitch.frequency(midi: midi, a4: a4)
                let seconds = base < 80 ? 1.2 : 0.6
                for signal in Signal.allCases {
                    for cents in [-20.0, 0, 20] {
                        let f = Synth.detune(base, cents: cents)
                        let buf = synth(signal, frequency: f, sampleRate: sampleRate, seconds: seconds)
                        results.append(CaseRunner.run(
                            signal: buf, sampleRate: sampleRate, trueFrequency: f,
                            category: signal.rawValue, centsTarget: cents, snrDB: .infinity,
                            method: method, a4: a4))
                    }
                }
            }
            return summarize(results, method: method)
        }
    }

    // MARK: - Synthesis dispatch

    private static func synth(_ s: Signal, frequency: Double, sampleRate: Double, seconds: Double) -> [Float] {
        switch s {
        case .pure: return Synth.pure(frequency: frequency, sampleRate: sampleRate, seconds: seconds)
        case .harmonic: return Synth.harmonic(fundamental: frequency, sampleRate: sampleRate, seconds: seconds)
        case .inharmonic: return Synth.inharmonicString(fundamental: frequency, sampleRate: sampleRate, seconds: seconds)
        }
    }

    // MARK: - Aggregation

    private static func summarize(_ results: [CaseResult], method: DetectionMethod) -> Summary {
        let clean = results.filter { !$0.snrDB.isFinite }
        let pooled = ErrorStats.from(clean.flatMap { $0.errors })
        // Headline octave-error rate is over clean tones (the achievable spec);
        // noise-case octave behaviour is reported separately in the noise table.
        let octRate = clean.isEmpty ? 0 : Double(clean.filter { $0.octaveError }.count) / Double(clean.count)
        let locks = clean.compactMap { $0.timeToLockMS }.sorted()
        let lockMedian = locks.isEmpty ? 0 : locks[locks.count / 2]
        return Summary(
            method: method,
            cleanAbsCents: pooled.meanAbs,
            cleanSigma: pooled.sigma,
            octaveErrorRate: octRate,
            worstAbsCents: pooled.maxAbs,
            lockMSMedian: lockMedian,
            cases: results.count
        )
    }

    private static func bucket(_ f: Double) -> String {
        if f < 82 { return "bass (<82 Hz)" }
        if f < 330 { return "mid (82–330 Hz)" }
        return "high (>330 Hz)"
    }

    // MARK: - CSV

    private static func csv(_ results: [CaseResult]) -> String {
        var lines = ["category,note,true_hz,cents_target,snr_db,n,mean_cents,abs_cents,sigma_cents,max_abs_cents,octave_error,lock_ms"]
        for r in results {
            let snr = r.snrDB.isFinite ? f2(r.snrDB) : "inf"
            let lock = r.timeToLockMS.map { f1($0) } ?? ""
            lines.append([
                r.category, r.note, f2(r.trueFrequency), f1(r.centsTarget), snr,
                "\(r.readings)", f3(r.stats.mean), f3(r.stats.meanAbs), f3(r.stats.sigma),
                f3(r.stats.maxAbs), r.octaveError ? "1" : "0", lock
            ].joined(separator: ","))
        }
        return lines.joined(separator: "\n")
    }

    // MARK: - Markdown

    private static func markdown(
        _ results: [CaseResult], summary: Summary,
        sampleRate: Double, a4: Double, dateLabel: String
    ) -> String {
        let clean = results.filter { !$0.snrDB.isFinite }
        var md = ""
        md += "# TunerEngine — measured accuracy\n\n"
        md += "_\(dateLabel). Method: **\(summary.method.rawValue.uppercased())**, "
        md += "\(Int(sampleRate)) Hz, A4 = \(Int(a4)) Hz. Deterministic (seeded)._\n\n"

        md += "## Headline\n\n"
        md += "| Metric | Value |\n|---|---|\n"
        md += "| Mean abs cents error (clean) | **\(f2(summary.cleanAbsCents))¢** |\n"
        md += "| Jitter σ (clean) | \(f2(summary.cleanSigma))¢ |\n"
        md += "| Worst-case abs error (clean) | \(f2(summary.worstAbsCents))¢ |\n"
        md += "| Octave-error rate (clean) | \(f2(summary.octaveErrorRate * 100))% |\n"
        md += "| Median time-to-lock (cold start) | \(f0(summary.lockMSMedian)) ms |\n"
        md += "| Cases | \(summary.cases) |\n\n"

        md += "## By signal type (clean)\n\n"
        md += "| Signal | n | mean ¢ | abs ¢ | σ ¢ | max ¢ |\n|---|---|---|---|---|---|\n"
        for s in Signal.allCases {
            let pooled = ErrorStats.from(clean.filter { $0.category == s.rawValue }.flatMap { $0.errors })
            md += "| \(s.rawValue) | \(pooled.count) | \(f2(pooled.mean)) | \(f2(pooled.meanAbs)) | \(f2(pooled.sigma)) | \(f2(pooled.maxAbs)) |\n"
        }
        md += "\n## By range (clean)\n\n"
        md += "| Range | n | abs ¢ | σ ¢ | max ¢ |\n|---|---|---|---|---|\n"
        for b in ["bass (<82 Hz)", "mid (82–330 Hz)", "high (>330 Hz)"] {
            let pooled = ErrorStats.from(clean.filter { bucket($0.trueFrequency) == b }.flatMap { $0.errors })
            md += "| \(b) | \(pooled.count) | \(f2(pooled.meanAbs)) | \(f2(pooled.sigma)) | \(f2(pooled.maxAbs)) |\n"
        }

        md += "\n## Noise robustness (inharmonic, abs cents vs SNR)\n\n"
        md += "| SNR (dB) | n | abs ¢ | σ ¢ | octave errors |\n|---|---|---|---|---|\n"
        for snr in [40.0, 20.0, 10.0] {
            let subset = results.filter { $0.snrDB == snr }
            let pooled = ErrorStats.from(subset.flatMap { $0.errors })
            let oct = subset.filter { $0.octaveError }.count
            md += "| \(Int(snr)) | \(pooled.count) | \(f2(pooled.meanAbs)) | \(f2(pooled.sigma)) | \(oct) |\n"
        }

        md += "\n## Octave safety on low strings (clean, 0¢)\n\n"
        md += "| Note | true Hz | abs ¢ | octave error |\n|---|---|---|---|\n"
        for midi in [23, 28, 33, 38, 43] {
            let f = Pitch.frequency(midi: midi, a4: a4)
            if let r = clean.first(where: { $0.category == "inharmonic" && abs($0.trueFrequency - f) < 0.5 }) {
                md += "| \(r.note) | \(f2(f)) | \(f2(r.stats.meanAbs)) | \(r.octaveError ? "⚠️ yes" : "no") |\n"
            }
        }

        md += "\n## Window / hop strategy (48 kHz)\n\n"
        md += "| Band | f0 | Window | Hop | Overlap |\n|---|---|---|---|---|\n"
        md += "| high | ≥250 Hz | 1024 (21 ms) | 256 (5.3 ms) | 75% |\n"
        md += "| mid | 80–250 Hz | 2048 (43 ms) | 512 (11 ms) | 75% |\n"
        md += "| low | <80 Hz | 4096 (85 ms) | 1024 (21 ms) | 75% |\n"
        md += "| acquire (cold) | unknown | 4096 (85 ms) | 1024 (21 ms) | 75% |\n\n"

        md += "## Method\n\n"
        md += "Each case synthesizes ~0.6–1.2 s of tone at a known frequency, feeds it through a fresh "
        md += "`PitchPipeline` in ~10 ms blocks, and scores the **steady-state** readings (after 300 ms, "
        md += "skipping the acquisition transient). Cents error is signal-relative "
        md += "(`1200·log₂(estimate/true)`), not quantised to the nearest note. Time-to-lock is cold-start "
        md += "(first confident reading within ±5¢); warm per-hop latency is the hop size above. "
        md += "Inharmonic tones use the stiff-string law `f_k = k·f0·√(1+B·k²)`, the case naive spectral-peak "
        md += "trackers fail. Numbers are reproducible via `swift run Benchmark`.\n"
        return md
    }

    // Formatting helpers.
    private static func f0(_ x: Double) -> String { String(format: "%.0f", x) }
    private static func f1(_ x: Double) -> String { String(format: "%.1f", x) }
    private static func f2(_ x: Double) -> String { String(format: "%.2f", x) }
    private static func f3(_ x: Double) -> String { String(format: "%.3f", x) }
}
